/*
 * AppDatabase — single source of truth for local persistence.
 *
 * FTS5 is configured through Room's `@Fts5` annotation on the entity; triggers are
 * auto-generated by Room. We also declare the `notes_fts` content-table mirror in
 * the open helper callback so the FTS shadow stays consistent if anyone writes
 * outside Room (e.g. during a migration).
 *
 * Migrations: ship `Migration_1_2` etc. as needed. For v1 we start at schema 1.
 */
package com.pulse.android.data.db

import androidx.room.Database
import androidx.room.Room
import androidx.room.RoomDatabase
import androidx.sqlite.db.SupportSQLiteDatabase
import android.content.Context
import com.pulse.android.data.model.ChatMessage
import com.pulse.android.data.model.Conversation
import com.pulse.android.data.model.Note
import com.pulse.android.data.model.NoteFts
import com.pulse.android.data.model.SyncQueueItem

@Database(
    entities = [
        Note::class,
        NoteFts::class,
        ChatMessage::class,
        Conversation::class,
        SyncQueueItem::class,
    ],
    version = 1,
    exportSchema = false,
)
abstract class AppDatabase : RoomDatabase() {
    abstract fun noteDao(): NoteDao
    abstract fun chatDao(): ChatMessageDao
    abstract fun syncQueueDao(): SyncQueueDao

    companion object {
        private const val DB_NAME = "pulse.db"

        @Volatile private var instance: AppDatabase? = null

        fun get(context: Context): AppDatabase = instance ?: synchronized(this) {
            instance ?: build(context).also { instance = it }
        }

        private fun build(context: Context): AppDatabase = Room
            .databaseBuilder(context.applicationContext, AppDatabase::class.java, DB_NAME)
            .addCallback(object : Callback() {
                override fun onCreate(db: SupportSQLiteDatabase) {
                    super.onCreate(db)
                    // Seed: 3-5 sample notes matching the design preview's "first run" set.
                    // Done in SQL so the on-disk DB is the same whether or not the app code
                    // is invoked.
                    val now = System.currentTimeMillis()
                    val day = 24L * 60 * 60 * 1000
                    val seed = listOf(
                        Note(
                            id = "seed-welcome",
                            title = "Welcome to Pulse",
                            body = """
                                # Welcome to Pulse

                                This is your first note. Pulse is a local-first markdown
                                notebook with **backlinks**, voice input, and a local
                                AI chat.

                                ## Try it

                                - Type [[ to link to another note
                                - Use the mic button in chat for voice input
                                - Search is offline (FTS5) — try a query

                                > Your notes are yours. No account. No cloud STT.
                            """.trimIndent(),
                            createdAt = now,
                            updatedAt = now,
                            pinned = true,
                            sizeBytes = 0,
                            backlinkCount = 3,
                        ),
                        Note(
                            id = "seed-standup",
                            title = "Daily standup — Aug 8",
                            body = """
                                ## Today
                                - [x] Ship onboarding
                                - [x] Wire up FTS
                                - [ ] Sync worker
                                - [ ] Model preflight
                            """.trimIndent(),
                            createdAt = now - day,
                            updatedAt = now - day,
                            pinned = false,
                            sizeBytes = 0,
                            backlinkCount = 0,
                        ),
                        Note(
                            id = "seed-release",
                            title = "Pulse v3.1 release notes",
                            body = """
                                # Pulse v3.1

                                - Backlinks panel on the editor
                                - Voice input (Android SpeechRecognizer, no cloud)
                                - Sync (PRO): end-to-end encrypted
                                - Bug fixes & polish
                            """.trimIndent(),
                            createdAt = now,
                            updatedAt = now,
                            pinned = false,
                            sizeBytes = 0,
                            backlinkCount = 12,
                        ),
                        Note(
                            id = "seed-pulse-web",
                            title = "Project: Pulse web (sync preview)",
                            body = """
                                # Pulse web

                                Status: in development.

                                Stack: Astro + React, Svelte islands.
                                Backend: Cloudflare Workers.
                            """.trimIndent(),
                            createdAt = now - day,
                            updatedAt = now - 2 * day,
                            pinned = false,
                            sizeBytes = 0,
                            backlinkCount = 24,
                        ),
                        Note(
                            id = "seed-reading",
                            title = "Reading list — Q3 2026",
                            body = """
                                # Reading list

                                - [ ] "Designing Data-Intensive Applications" (re-read)
                                - [ ] Papers on local-first sync (Martin Kleppmann)
                                - [x] "Crafting Interpreters" — finished
                            """.trimIndent(),
                            createdAt = now - 3 * day,
                            updatedAt = now - 4 * day,
                            pinned = false,
                            sizeBytes = 0,
                            backlinkCount = 2,
                        ),
                    )
                    seed.forEach { note ->
                        db.execSQL(
                            "INSERT INTO notes(id, title, body, createdAt, updatedAt, pinned, sizeBytes, backlinkCount) " +
                                "VALUES (?, ?, ?, ?, ?, ?, ?, ?)",
                            arrayOf(
                                note.id, note.title, note.body,
                                note.createdAt, note.updatedAt,
                                if (note.pinned) 1 else 0, note.sizeBytes, note.backlinkCount,
                            ),
                        )
                        // Mirror into FTS5. The `rowid` must match the source row.
                        db.execSQL(
                            "INSERT INTO notes_fts(rowid, title, body) VALUES ((SELECT rowid FROM notes WHERE id = ?), ?, ?)",
                            arrayOf<Any>(note.id, note.title, note.body),
                        )
                    }
                }
            })
            .fallbackToDestructiveMigration()  // v1 only; ship migrations from v2
            .build()
    }
}
